/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   entity__init
                     (Entity         *message)
{
  static Entity init_value = ENTITY__INIT;
  *message = init_value;
}
size_t entity__get_packed_size
                     (const Entity *message)
{
  assert(message->base.descriptor == &entity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t entity__pack
                     (const Entity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &entity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t entity__pack_to_buffer
                     (const Entity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &entity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Entity *
       entity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Entity *)
     protobuf_c_message_unpack (&entity__descriptor,
                                allocator, len, data);
}
void   entity__free_unpacked
                     (Entity *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &entity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_message__init
                     (ClientMessage         *message)
{
  static ClientMessage init_value = CLIENT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_message__get_packed_size
                     (const ClientMessage *message)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_message__pack
                     (const ClientMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_message__pack_to_buffer
                     (const ClientMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMessage *)
     protobuf_c_message_unpack (&client_message__descriptor,
                                allocator, len, data);
}
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &client_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_message__init
                     (ResponseMessage         *message)
{
  static ResponseMessage init_value = RESPONSE_MESSAGE__INIT;
  *message = init_value;
}
size_t response_message__get_packed_size
                     (const ResponseMessage *message)
{
  assert(message->base.descriptor == &response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_message__pack
                     (const ResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_message__pack_to_buffer
                     (const ResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseMessage *
       response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseMessage *)
     protobuf_c_message_unpack (&response_message__descriptor,
                                allocator, len, data);
}
void   response_message__free_unpacked
                     (ResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   display_update__init
                     (DisplayUpdate         *message)
{
  static DisplayUpdate init_value = DISPLAY_UPDATE__INIT;
  *message = init_value;
}
size_t display_update__get_packed_size
                     (const DisplayUpdate *message)
{
  assert(message->base.descriptor == &display_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t display_update__pack
                     (const DisplayUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &display_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t display_update__pack_to_buffer
                     (const DisplayUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &display_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DisplayUpdate *
       display_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DisplayUpdate *)
     protobuf_c_message_unpack (&display_update__descriptor,
                                allocator, len, data);
}
void   display_update__free_unpacked
                     (DisplayUpdate *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &display_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   connect_display_response__init
                     (ConnectDisplayResponse         *message)
{
  static ConnectDisplayResponse init_value = CONNECT_DISPLAY_RESPONSE__INIT;
  *message = init_value;
}
size_t connect_display_response__get_packed_size
                     (const ConnectDisplayResponse *message)
{
  assert(message->base.descriptor == &connect_display_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect_display_response__pack
                     (const ConnectDisplayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connect_display_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect_display_response__pack_to_buffer
                     (const ConnectDisplayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connect_display_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectDisplayResponse *
       connect_display_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectDisplayResponse *)
     protobuf_c_message_unpack (&connect_display_response__descriptor,
                                allocator, len, data);
}
void   connect_display_response__free_unpacked
                     (ConnectDisplayResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &connect_display_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor entity__field_descriptors[7] =
{
  {
    "entity_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Entity, entity_type),
    &entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Entity, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "points",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Entity, points),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Entity, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Entity, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Entity, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret_code",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Entity, secret_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned entity__field_indices_by_name[] = {
  1,   /* field[1] = ch */
  5,   /* field[5] = direction */
  0,   /* field[0] = entity_type */
  2,   /* field[2] = points */
  3,   /* field[3] = pos_x */
  4,   /* field[4] = pos_y */
  6,   /* field[6] = secret_code */
};
static const ProtobufCIntRange entity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor entity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Entity",
  "Entity",
  "Entity",
  "",
  sizeof(Entity),
  7,
  entity__field_descriptors,
  entity__field_indices_by_name,
  1,  entity__number_ranges,
  (ProtobufCMessageInit) entity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_message__field_descriptors[5] =
{
  {
    "entity_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, entity_type),
    &entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, msg_type),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret_code",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, secret_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_code",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, client_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_message__field_indices_by_name[] = {
  4,   /* field[4] = client_code */
  2,   /* field[2] = content */
  0,   /* field[0] = entity_type */
  1,   /* field[1] = msg_type */
  3,   /* field[3] = secret_code */
};
static const ProtobufCIntRange client_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor client_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientMessage",
  "ClientMessage",
  "ClientMessage",
  "",
  sizeof(ClientMessage),
  5,
  client_message__field_descriptors,
  client_message__field_indices_by_name,
  1,  client_message__number_ranges,
  (ProtobufCMessageInit) client_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_message__field_descriptors[3] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResponseMessage, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ResponseMessage, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret_code",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ResponseMessage, secret_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_message__field_indices_by_name[] = {
  1,   /* field[1] = score */
  2,   /* field[2] = secret_code */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange response_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseMessage",
  "ResponseMessage",
  "ResponseMessage",
  "",
  sizeof(ResponseMessage),
  3,
  response_message__field_descriptors,
  response_message__field_indices_by_name,
  1,  response_message__number_ranges,
  (ProtobufCMessageInit) response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor display_update__field_descriptors[3] =
{
  {
    "entity",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdate, entity),
    &entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnect",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdate, disconnect),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_l_bumped",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DisplayUpdate, id_l_bumped),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned display_update__field_indices_by_name[] = {
  1,   /* field[1] = disconnect */
  0,   /* field[0] = entity */
  2,   /* field[2] = id_l_bumped */
};
static const ProtobufCIntRange display_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor display_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DisplayUpdate",
  "DisplayUpdate",
  "DisplayUpdate",
  "",
  sizeof(DisplayUpdate),
  3,
  display_update__field_descriptors,
  display_update__field_indices_by_name,
  1,  display_update__number_ranges,
  (ProtobufCMessageInit) display_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor connect_display_response__field_descriptors[5] =
{
  {
    "lizard",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ConnectDisplayResponse, n_lizard),
    offsetof(ConnectDisplayResponse, lizard),
    &entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "npc",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ConnectDisplayResponse, n_npc),
    offsetof(ConnectDisplayResponse, npc),
    &entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_lizards",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ConnectDisplayResponse, n_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n__npc",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ConnectDisplayResponse, n__npc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_port",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ConnectDisplayResponse, address_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect_display_response__field_indices_by_name[] = {
  4,   /* field[4] = address_port */
  0,   /* field[0] = lizard */
  3,   /* field[3] = n__npc */
  2,   /* field[2] = n_lizards */
  1,   /* field[1] = npc */
};
static const ProtobufCIntRange connect_display_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor connect_display_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnectDisplayResponse",
  "ConnectDisplayResponse",
  "ConnectDisplayResponse",
  "",
  sizeof(ConnectDisplayResponse),
  5,
  connect_display_response__field_descriptors,
  connect_display_response__field_indices_by_name,
  1,  connect_display_response__number_ranges,
  (ProtobufCMessageInit) connect_display_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue entity_type__enum_values_by_number[3] =
{
  { "LIZARD", "ENTITY_TYPE__LIZARD", 0 },
  { "ROACH", "ENTITY_TYPE__ROACH", 1 },
  { "WASP", "ENTITY_TYPE__WASP", 2 },
};
static const ProtobufCIntRange entity_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex entity_type__enum_values_by_name[3] =
{
  { "LIZARD", 0 },
  { "ROACH", 1 },
  { "WASP", 2 },
};
const ProtobufCEnumDescriptor entity_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EntityType",
  "EntityType",
  "EntityType",
  "",
  3,
  entity_type__enum_values_by_number,
  3,
  entity_type__enum_values_by_name,
  1,
  entity_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[4] =
{
  { "UP", "DIRECTION__UP", 0 },
  { "DOWN", "DIRECTION__DOWN", 1 },
  { "LEFT", "DIRECTION__LEFT", 2 },
  { "RIGHT", "DIRECTION__RIGHT", 3 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  4,
  direction__enum_values_by_number,
  4,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[3] =
{
  { "CONNECT", "MESSAGE_TYPE__CONNECT", 0 },
  { "MOVE", "MESSAGE_TYPE__MOVE", 1 },
  { "DISCONNECT", "MESSAGE_TYPE__DISCONNECT", 2 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[3] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 2 },
  { "MOVE", 1 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  3,
  message_type__enum_values_by_number,
  3,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
