# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0emessages.proto\"\x98\x01\n\x06\x45ntity\x12 \n\x0b\x65ntity_type\x18\x01 \x02(\x0e\x32\x0b.EntityType\x12\n\n\x02\x63h\x18\x02 \x02(\t\x12\x0e\n\x06points\x18\x03 \x02(\r\x12\r\n\x05pos_x\x18\x04 \x02(\r\x12\r\n\x05pos_y\x18\x05 \x02(\r\x12\x1d\n\tdirection\x18\x06 \x02(\x0e\x32\n.Direction\x12\x13\n\x0bsecret_code\x18\x07 \x02(\x05\"\x8c\x01\n\rClientMessage\x12 \n\x0b\x65ntity_type\x18\x01 \x02(\x0e\x32\x0b.EntityType\x12\x1e\n\x08msg_type\x18\x02 \x02(\x0e\x32\x0c.MessageType\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\x11\x12\x13\n\x0bsecret_code\x18\x04 \x02(\x11\x12\x13\n\x0b\x63lient_code\x18\x05 \x02(\x11\"F\n\x0fResponseMessage\x12\x0f\n\x07success\x18\x01 \x02(\r\x12\r\n\x05score\x18\x02 \x02(\x11\x12\x13\n\x0bsecret_code\x18\x03 \x02(\x11\"Q\n\rDisplayUpdate\x12\x17\n\x06\x65ntity\x18\x01 \x02(\x0b\x32\x07.Entity\x12\x12\n\ndisconnect\x18\x02 \x02(\r\x12\x13\n\x0bid_l_bumped\x18\x03 \x02(\x11\"\x80\x01\n\x16\x43onnectDisplayResponse\x12\x17\n\x06lizard\x18\x01 \x03(\x0b\x32\x07.Entity\x12\x14\n\x03npc\x18\x02 \x03(\x0b\x32\x07.Entity\x12\x11\n\tn_lizards\x18\x03 \x02(\x05\x12\x0e\n\x06n__npc\x18\x04 \x02(\x05\x12\x14\n\x0c\x61\x64\x64ress_port\x18\x05 \x02(\t*-\n\nEntityType\x12\n\n\x06LIZARD\x10\x00\x12\t\n\x05ROACH\x10\x01\x12\x08\n\x04WASP\x10\x02*2\n\tDirection\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03*4\n\x0bMessageType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x08\n\x04MOVE\x10\x01\x12\x0e\n\nDISCONNECT\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ENTITYTYPE = _descriptor.EnumDescriptor(
  name='EntityType',
  full_name='EntityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIZARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROACH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WASP', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=602,
  serialized_end=647,
)
_sym_db.RegisterEnumDescriptor(_ENTITYTYPE)

EntityType = enum_type_wrapper.EnumTypeWrapper(_ENTITYTYPE)
_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=649,
  serialized_end=699,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=701,
  serialized_end=753,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
LIZARD = 0
ROACH = 1
WASP = 2
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3
CONNECT = 0
MOVE = 1
DISCONNECT = 2



_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='Entity.entity_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ch', full_name='Entity.ch', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='Entity.points', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='Entity.pos_x', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='Entity.pos_y', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Entity.direction', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret_code', full_name='Entity.secret_code', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=171,
)


_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='ClientMessage.entity_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='ClientMessage.msg_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='ClientMessage.content', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret_code', full_name='ClientMessage.secret_code', index=3,
      number=4, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_code', full_name='ClientMessage.client_code', index=4,
      number=5, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=314,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ResponseMessage.success', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='ResponseMessage.score', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret_code', full_name='ResponseMessage.secret_code', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=386,
)


_DISPLAYUPDATE = _descriptor.Descriptor(
  name='DisplayUpdate',
  full_name='DisplayUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='DisplayUpdate.entity', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='DisplayUpdate.disconnect', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_l_bumped', full_name='DisplayUpdate.id_l_bumped', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=469,
)


_CONNECTDISPLAYRESPONSE = _descriptor.Descriptor(
  name='ConnectDisplayResponse',
  full_name='ConnectDisplayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lizard', full_name='ConnectDisplayResponse.lizard', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='npc', full_name='ConnectDisplayResponse.npc', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_lizards', full_name='ConnectDisplayResponse.n_lizards', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n__npc', full_name='ConnectDisplayResponse.n__npc', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_port', full_name='ConnectDisplayResponse.address_port', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=600,
)

_ENTITY.fields_by_name['entity_type'].enum_type = _ENTITYTYPE
_ENTITY.fields_by_name['direction'].enum_type = _DIRECTION
_CLIENTMESSAGE.fields_by_name['entity_type'].enum_type = _ENTITYTYPE
_CLIENTMESSAGE.fields_by_name['msg_type'].enum_type = _MESSAGETYPE
_DISPLAYUPDATE.fields_by_name['entity'].message_type = _ENTITY
_CONNECTDISPLAYRESPONSE.fields_by_name['lizard'].message_type = _ENTITY
_CONNECTDISPLAYRESPONSE.fields_by_name['npc'].message_type = _ENTITY
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['DisplayUpdate'] = _DISPLAYUPDATE
DESCRIPTOR.message_types_by_name['ConnectDisplayResponse'] = _CONNECTDISPLAYRESPONSE
DESCRIPTOR.enum_types_by_name['EntityType'] = _ENTITYTYPE
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Entity)
  ))
_sym_db.RegisterMessage(Entity)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ClientMessage)
  ))
_sym_db.RegisterMessage(ClientMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)

DisplayUpdate = _reflection.GeneratedProtocolMessageType('DisplayUpdate', (_message.Message,), dict(
  DESCRIPTOR = _DISPLAYUPDATE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:DisplayUpdate)
  ))
_sym_db.RegisterMessage(DisplayUpdate)

ConnectDisplayResponse = _reflection.GeneratedProtocolMessageType('ConnectDisplayResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTDISPLAYRESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ConnectDisplayResponse)
  ))
_sym_db.RegisterMessage(ConnectDisplayResponse)


# @@protoc_insertion_point(module_scope)
